In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [3]:
print(a.shape)

(3,)


In [4]:
print(a[0],a[1],a[2])

1 2 3


In [5]:
a[0]=5

In [6]:
print(a)

[5 2 3]


In [8]:
b=np.array([[1,2,3],[4,5,6]])

In [9]:
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
print(b.shape)

(2, 3)


In [11]:
print(a)

[5 2 3]


In [12]:
print(b[0,0],b[0,1],b[1,0])

1 2 4


In [13]:
a=np.zeros((2,2))

In [14]:
print(a)

[[ 0.  0.]
 [ 0.  0.]]


In [15]:
print(np.ones((1,2)))

[[ 1.  1.]]


In [16]:
print(np.full((2,2),7))

[[7 7]
 [7 7]]


In [17]:
print(np.eye(2))

[[ 1.  0.]
 [ 0.  1.]]


In [21]:
print(np.random.random((2,2)))

[[ 0.47919113  0.24646477]
 [ 0.48186022  0.96829373]]


In [29]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [24]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
b=a[:2,1:3]

In [26]:
print(b)

[[2 3]
 [6 7]]


In [27]:
b[0,0]=77

In [28]:
print(a)

[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [30]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

row_r1=a[1,:]
row_r2=a[1:2,:]
print(row_r1,row_r1.shape)

[5 6 7 8] (4,)


In [31]:
print(row_r2,row_r2.shape)

[[5 6 7 8]] (1, 4)


In [32]:
col_r1=a[:,1]
col_r2=a[:,1:2]

In [33]:
print(col_r1,col_r1.shape)

[ 2  6 10] (3,)


In [34]:
print(col_r2,col_r2.shape)

[[ 2]
 [ 6]
 [10]] (3, 1)


In [1]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])

In [2]:
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [3]:
print(a[[0,1,2],[0,1,0]])

[1 4 5]


In [4]:
print(np.array([a[0,0],a[1,1],a[2,0]]))

[1 4 5]


In [9]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [10]:
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
b=np.array([0,2,0,1])

In [12]:
print(b)

[0 2 0 1]


In [13]:
print(a[np.arange(4),b])

[ 1  6  7 11]


In [14]:
a[np.arange(4),b]+=10

In [15]:
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [16]:
a=np.array([[1,2],[3,4],[5,6]])

In [17]:
bool_idx=(a>2)

In [18]:
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [19]:
print(a[bool_idx])

[3 4 5 6]


In [20]:
print(a[a>2])

[3 4 5 6]
