In [1]:
import numpy as np

In [2]:
s=np.array(5)

In [3]:
s

array(5)

In [4]:
s.shape

()

In [5]:
x=s+3

In [6]:
x

8

In [7]:
s.shape

()

In [21]:
v=np.array([1,2,3])

In [9]:
v.shape

(3,)

In [16]:
v=np.array([[1],[2],[3]])

In [17]:
v.shape

(3, 1)

In [18]:
x=v[1]

In [22]:
x

array([2])

In [23]:
v[1:]

array([2, 3])

In [26]:
m=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [27]:
m.shape

(3, 3)

In [29]:
m[1][2]

6

In [30]:
v=np.array([1,2,3,4])

In [31]:
x=v.reshape(1,4)

In [32]:
x

array([[1, 2, 3, 4]])

In [33]:
x=v[None,:]

In [34]:
x

array([[1, 2, 3, 4]])

In [35]:
x=v[:,None]

In [36]:
x

array([[1],
       [2],
       [3],
       [4]])

In [53]:
v=np.array([1,2,3,4,5])

In [54]:
x=v*2

In [55]:
x

array([ 2,  4,  6,  8, 10])

In [56]:
x=v**2

In [57]:
x

array([ 1,  4,  9, 16, 25])

In [58]:
x=x*0

In [59]:
x

array([0, 0, 0, 0, 0])

In [60]:
m=np.array([[1,2,3],[4,5,6]])

In [61]:
n=m*0.25

In [62]:
n

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ]])

In [63]:
m*n

array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

In [64]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
m.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [66]:
m_t=m.T

In [67]:
m_t

array([[1, 4],
       [2, 5],
       [3, 6]])

In [68]:
m_t[1,1]

5

In [69]:
m_t[1][1]

5

In [1]:
import numpy as np

In [2]:
p=np.empty((3))
Pz=np.empty((3))

plu=float(input('plu'))
plv=float(input('plv'))

u=4/800*plu
v=3/600*plv
f=5
p[0]=u
p[1]=v
p[2]=f

Pz=1/f*p
print(u,v)
print(Pz[0],Pz[1],Pz[2])
print(Pz)

plu20
plv-80
0.1 -0.4
0.020000000000000004 -0.08000000000000002 1.0
[ 0.02 -0.08  1.  ]
