arccos求法：附带弧度与角度互换

In [ ]:
import math
a=math.degrees(math.acos(0))
print(a)

In [ ]:
a=math.radians(180)
print(a)

乘法不可以省略* 号：

In [ ]:
R=3
A=2*R
print(A)

次方求法：

In [ ]:
3**2

In [ ]:
a=7
b=4
c=5
h=min(a,b,c)
print(h)

<table><tr><td bgcolor=#F4A465>
<p align="center">
<font color=#228B22 size=5 face="San Francisco">
<!-- <font color=#228B22 size=4 face="Heiti SC"> -->
Aufgabe 1--Farbmodell</font><br />
<font color=#228B22 size=4 face="San Francisco">Transformieren Sie die im RGB-Modell angegebene Farbe (120, 80, 210) in das HSIFormat. Onlinefrage Nr. 1: Wie ist der Hue-Wert der Farbe aus Aufgabe 1? (a) 39:1◦ (b) 132; 8◦ (c) 257; 5◦
</font>
</p>
</td></tr></table>


In [ ]:
import math
# ctrl+/ 快速注释
# R=input('Input R:')
# G=input('Input G:')
# B=input('Input B:')
# R=float(R)
# G=float(G)
# B=float(B)
R=120
G=80
B=210
H=0

c=math.acos((2*R-G-B)/(2*math.sqrt((R-G)**2+(R-B)*(G-B))))

if B<G:
    H=c
else:
    H=360-math.degrees(c)

S=1-3/((R+G+B)*min(R,G,B))

I=1/3*(R+G+B)

print('H=',H,'\nS=',S,'\nI=',I)

<table><tr><td bgcolor=#F4A465>
<p align="justify">
<font color=#228B22 size=5 face="San Francisco">
Aufgabe 2---Lochkameramodell</font><br />
<font color=#228B22 size=4 face="San Francisco">
Gegeben sind zwei Kameras. Beide Kameras zeigen in z-Richtung (d.h. ihre Bildebenen
sind parallel) und sind nur in x-Richtung zueinander verschoben. Das in der Vorlesung
vorgestellte Lochkameramodell in Positivlage soll verwendet werden; es gelten also die
Gleichungen fur das Lochkameramodell ohne Minuszeichen. Die beiden Projektionszen- ¨
tren der Kameras haben den Abstand b = 100 mm. Das Kamerakoordinatensystem jeder
Kamera hat seinen Ursprung im jeweiligen Projektionszentrum, die x-Achse zeigt nach
rechts, die y-Achse nach unten und die z-Achse nach vorne. Das Bildkoordinatensystem
1jeder Kamera hat seinen Ursprung in der Mitte des CCD-Chips. Das Weltkoordinatensystem ist identisch mit dem Kamerakoordinatensystem der linken Kamera. Beide Kameras
besitzen eine Brennweite von f = 5 mm, einen CCD-Chip von 4 mm × 3 mm Gr¨ oße,
mit 800 × 600 CCD-Zellen. Es kann angenommen werden, dass die einzelnen CCD-Zellen
luckenlos aneinander anschließen, quadratisch und gleich groß sind.
</font>
</p>
</td></tr></table>


<table><tr><td bgcolor=#F4A465>
<p align="justify">
<font color=#228B22 size=4 face="San Francisco">
<!-- <font color=#228B22 size=4 face="Heiti SC"> -->
矩阵计算 https://blog.csdn.net/taoyanqi8932/article/details/52703686
</font>
</p>
</td></tr></table>

In [ ]:
from numpy import *
a1=array([1,2,3])
a1=a1*3
X=a1[0]
Y=a1[1]
Z=a1[2]
print('a1=',a1)
print('X=',X,'\nY=',Y,'\nZ=',Z)

In [ ]:
#Methode 1
import numpy as np
#initial
p=np.empty((3))
P=np.empty((3))

# #Methode 2
# from numpy import *
# #initial
# p=empty((3))
# P=empty((3))

#input Punkt P 
P[0]=input('Input X=')
P[1]=input('Input Y=')
P[2]=input('Input Z=')
X,Y,Z=P[0],P[1],P[2]
print('\nP=',P,'\nX=',X,'\nY=',Y,'\nZ=',Z)

#input Brennweite und brechnen den Bildpunkt
f=5
p=f/Z*P
u=p[0]
v=p[1]
print('\np=',p,'\nu=',u,'\nv=',v)



<table><tr><td bgcolor=#F4A465>
<p align="center">
<font color=#228B22 size=5 face="San Francisco">
2.a<br />
</font>
<font color=#228B22 size=4 face="San Francisco">
Skizzieren Sie die Anordnung. Auf welchen Bildpunkt p(u; v) mit u; v 2 R der linken
Kamera wird der Punkt P (120 mm; 90 mm; 750 mm) abgebildet?
</font>
</p>
</td></tr></table>

In [ ]:
#Methode 1
import numpy as np
#initial
p=np.empty((3))
P=np.empty((3))

#input Punkt P 
P[0]=120
P[1]=90
P[2]=750
X,Y,Z=P[0],P[1],P[2]
print('\nP=',P,'\nX=',X,'mm\nY=',Y,'mm\nZ=',Z,'mm')

#input Brennweite und brechnen den Bildpunkt
f=5
p=f/Z*P
u=p[0]
v=p[1]
print('\np=',p,'\nu=',u,'mm\nv=',v,'mm')

<table><tr><td bgcolor=#F4A465>
<p align="center">
<font color=#228B22 size=5 face="San Francisco">
2.b<br />
</font>
<font color=#228B22 size=4 face="San Francisco">
Die linke Kamera liefert einen Bildpunkt pl(20; −80) (in Pixeln). Bestimmen Sie die im
Kamerakoordinatensystem der linken Kamera definierte Gerade gl aller Punkte, die sich
auf den Bildpunkt pl abbilden. Die rechte Kamera liefert einen Bildpunkt pr(−80; −80).
Bestimmen Sie die im Kamerakoordinatensystem der rechten Kamera definierte Gerade
gr aller Punkte, die sich auf den Bildpunkt pr abbilden. Gehen Sie bei den Berechnungen
von einer als Punkt idealisierten CCD-Zelle aus.
</font>
</p>
</td></tr></table>

In [ ]:
import numpy as np
# initialisierung
pl=np.empty((3))
pr=np.empty((3))
Pzl=np.empty((3))
Pzr=np.empty((3))

# input Bildpunkt pl (in Pixeln)
plu=float(input('Input Pixel plu='))
plv=float(input('Input Pixel plv='))
# Bildpunkt pl(ul,vl,f) in mm
ul=4/800*plu
vl=3/600*plv
f=5
pl[0]=ul
pl[1]=vl
pl[2]=f
#Verwenden den Zwischenwert Pzl um gl im Kamerakoordinatensystem der linken Kamera zu beschreiben
Pzl=pl/f
# print(ul,'mm',vl,'mm') #in mm
print('Gerade gl im Kamerakoordinatensystem der linken Kamera:\n    xl=',Pzl[0],'*zl\n    yl=',Pzl[1],'*zl\n    zl=zl\n')

# input Bildpunkt pr (in Pixeln)
pru=float(input('Input Pixel pru='))
prv=float(input('Input Pixel prv='))
# Bildpunkt pr(ur,vr,f) in mm
ur=4/800*pru
vr=3/600*prv
f=5
pr[0]=ur
pr[1]=vr
pr[2]=f
#Verwenden den Zwischenwert Pzr um gr im Kamerakoordinatensystem der rechten Kamera zu beschreiben
Pzr=pr/f
# print(ur,'mm',vr,'mm') #in mm
print('Gerade gr im Kamerakoordinatensystem der rechten Kamera:\n    xr=',Pzr[0],'*zr\n    yr=',Pzr[1],'*zr\n    zr=zr\n')


In [ ]:
from sympy import *
zl=Symbol('zl')
zr=Symbol('zr')
print (solve([0.02*zl+0.08*zr-100,-0.08*zl+0.08*zr],[zl,zr]))

<table><tr><td bgcolor=#F4A465>
<p align="center">
<font color=#228B22 size=5 face="San Francisco">
2.c<br />
</font>
<font color=#228B22 size=4 face="San Francisco">
Bestimmen Sie die Koordinatentransformation vom rechten Kamerakoordinatensystem in
das Weltkoordinatensystem und berechnen Sie mit deren Hilfe die Darstellung der Gerade
gr im Weltkoordinatensystem. Berechnen Sie nun den Schnitt der (im Weltkoordinatensystem dargestellten) Geraden gl und gr und somit die Koordinaten des Punktes S, der
sich auf die Bildpunkte pl und pr abgebildet hat.
</font>
</p>
</td></tr></table>

In [ ]:
import numpy as np
from sympy import *
# initialisierung
pl=np.empty((3))
pr=np.empty((3))
Pzl=np.empty((3))
Pzr=np.empty((3))

# input Bildpunkt pl (in Pixeln)
plu=float(input('Input Pixel plu='))
plv=float(input('Input Pixel plv='))
# Bildpunkt pl(ul,vl,f) in mm
ul=4/800*plu
vl=3/600*plv
f=5
pl[0]=ul
pl[1]=vl
pl[2]=f
#Verwenden den Zwischenwert Pzl
Pzl=pl/f

# input Bildpunkt pr (in Pixeln)
pru=float(input('Input Pixel pru='))
prv=float(input('Input Pixel prv='))
# Bildpunkt pr(ur,vr,f) in mm
ur=4/800*pru
vr=3/600*prv
f=5
pr[0]=ur
pr[1]=vr
pr[2]=f
#Verwenden den Zwischenwert Pzr
Pzr=pr/f


zl=Symbol('zl')
zr=Symbol('zr')
print (solve([Pzl[0]*zl-Pzr[0]*zr-100,Pzl[1]*zl-Pzr[1]*zr],[zl,zr]))

<table><tr><td bgcolor=#F4A465>
<p align="center">
<font color=#228B22 size=5 face="San Francisco">
2.d<br />
</font>
<font color=#228B22 size=4 face="San Francisco">
Aufgrund von Bildrauschen wird durch die Bildverarbeitung der Punkt p0 l = (20; −81)
statt pl berechnet. Berechnen Sie die entsprechende Gerade gl0. Was hat dies zur Folge?
Wie l¨ asst sich dennoch ein 3D-Punkt berechnen? Beschreiben Sie Ihren Ansatz und stellen Sie eine allgemeine Gleichung fur die Berechnung der L ¨ ¨ osung auf { eine Rechnung mit
Zahlen wird nicht verlangt.
</font>
</p>
</td></tr></table>


In [ ]:
import numpy as np
# initialisierung
pl_=np.empty((3))
Pzl_=np.empty((3))

# input Bildpunkt pl_ (in Pixeln)
plu_=float(input('Input Pixel plu_='))
plv_=float(input('Input Pixel plv_='))
# Bildpunkt pl(ul_,vl_,f) in mm
ul_=4/800*plu_
vl_=3/600*plv_
f=5
pl[0]=ul_
pl[1]=vl_
pl[2]=f
#Verwenden den Zwischenwert Pzl_ um gl_ im Kamerakoordinatensystem der linken Kamera zu beschreiben
Pzl_=pl_/f
# print(ul_,'mm',vl_,'mm') #in mm
print('Gerade gl_ im Kamerakoordinatensystem der linken Kamera:\n    xl_=',Pzl_[0],'*zl_\n    yl_=',Pzl_[1],'*zl_\n    zl_=zl_\n')


<table><tr><td bgcolor=#F4A465>
<p align="justify">
<font color=#228B22 size=5 face="San Francisco">
Aufgabe 3--Kontrastanpassung</font><br />
</p>
</td></tr></table>

<table><tr><td bgcolor=#F4A465>
<p align="center">
<font color=#228B22 size=5 face="San Francisco">
3.a<br />
</font>
<font color=#228B22 size=4 face="San Francisco">
Berechnen Sie das Ergebnisbild nach Ausfuhrung einer Spreizung für die untenstehende Bildmatrix B.<br /><br />
https://blog.csdn.net/dongtingzhizi/article/details/89735690
</font>
</p>
</td></tr></table>

In [ ]:
#Spreizung
#Die Spreizung ist eine affine Punktoperation
#Nachteil:
#  In der Praxis nicht robust
#  Nur unter optimalen Bedingungen anwendbar

import numpy as np
from numpy import *

# Algorithmus 11
# Die Spreizung berechnet in einem Bild zunächst die
# minimale Intensität min und die maximale Intensität max
def BerechneMinMax(I):
    min=q
    max=0
    u=0
    v=0    
    while v<4:
        while u<3:
            if I[u,v]<min:
                min=I[u,v]
            elif I[u,v]>max:
                max=I[u,v]
            u=u+1        
        v=v+1
        u=0
    return min,max

# Algorithmus 8
def AffinePunktoperatioin(I,a,b):
    v=0
    u=0
    while v<4:
        while u<3:
            g=a*I[u,v]+b                   #Wegen Python3+ round() nicht wie gewuenscht funktioniert
            g_=round(a*I[u,v]+b)
            if (g-g_)>=0.5:
                g=g_+1
            else:
                g=g_
            if g<0:
                I[u,v]=0
            elif g>q:
                I[u,v]=q
            else:
                I[u,v]=g
            u=u+1
        v=v+1
        u=0
    return I

# Algorithmus 12
# Anschließend wird das Intervall [min, max] linear auf
# [0, 255] abgebildet und es werden entsprechend die
# Intensitäten im Bild angepasst
def Spreize(I):
    minmax=BerechneMinMax(I)
    Min=minmax[0]
    Max=minmax[1]
    I_=I
    if Min==Max:
        print('Bild I ist homogen')
    else:
        a=q/(Max-Min)
        b=-q*Min/(Max-Min)
        I_=AffinePunktoperatioin(I_,a,b)
    return I_



q=255
B=mat([[180,80,140,110],
       [0,110,140,80],
       [255,110,180,140]])
B_=Spreize(B)
print('B_=\n',B_)

<table><tr><td bgcolor=#F4A465>
<p align="center">
<font color=#228B22 size=5 face="San Francisco">
3.b<br />
</font>
<font color=#228B22 size=4 face="San Francisco">
Berechnen Sie das Histogramm H(x) und das akkumulierte Histogramm Ha(x) für die
Bildmatrix B. Berechnen Sie nun das Ergebnisbild nach Ausführung einer Histogramm- 
dehnung. Verwenden Sie dazu die Quantile 0.1 und 0.9. Runden Sie dabei alle Einträge
durch kaufmännisches (="normales") Runden auf ganzzahlige Werte.<br />
Onlinefrage Nr. 3:
Wie groß ist die Summe aller Einträge der neuen Bildmatrix aus Teilaufgabe 3.b? (a) 1341 (b) 1455 (c) 1137<br />
<br />round()  https://www.cnblogs.com/anpengapple/p/6507271.html
</font>
</p>
</td></tr></table>

In [73]:
# Histogrammdehnung
# Die Histogrammdehnung ist eine Verbesserung der Spreizung
# Anstatt der minimalen bzw. maximalen Intensität werden
# Quantile verwendet, um tatsächliche Maxima im Histogramm zu erkennen
# Die Histogrammdehnung ist eine affine Punktoperation

import numpy as np
from numpy import *

# Algorithmus 8
def AffinePunktoperatioin(I,a,b):
    v=0
    u=0
    while u<3:
        while v<4:
            g=a*I[u,v]+b                   #Wegen Python3+ round() nicht wie gewuenscht funktioniert
            g_=round(a*I[u,v]+b)
            if (g-g_)>=0.5:
                g=g_+1
            else:
                g=g_
#             print(g_)    
            if g<0:
                I[u,v]=0
            elif g>q:
                I[u,v]=q
            else:
                I[u,v]=g
#             print(I[u,v])
            v=v+1
        u=u+1
        v=0
    return I

# Algorithmus 14
def BrechneQuantil(Ha,p):
    x=0
    while x<(q+1):
        if Ha[x]>=p*Ha[q]:
            v=x
            return v
        else:
            x=x+1

# Algorithmus 13
def BrechneAkkumuliertesHistogramm(H):
    Ha=np.empty((q+1))
    Ha[0]=H[0]
    x=1
    while x<(q+1):
        Ha[x]=Ha[x-1]+H[x]
        x=x+1
    return Ha

# Algorithmus 9
def BrechneGrauwertHistogramm(I):
    x=0
    u=0
    v=0
    H=np.empty((q+1))
    while x<(q+1):
        H[x]=0
        x=x+1
    while v<4:
        while u<3:
            H[I[u,v]]=H[I[u,v]]+1
            u=u+1
        v=v+1
        u=0
    return H

# Algorithmus 15
def HistogrammDehnung(I,pmin,pmax):
    H=BrechneGrauwertHistogramm(I)
    Ha=BrechneAkkumuliertesHistogramm(H)
    min=BrechneQuantil(Ha,pmin)
    max=BrechneQuantil(Ha,pmax)
    if min==max:
        print('Bild I ist homogen')
        return None
    else:
        a=q/(max-min)
        b=-q*min/(max-min)
#         print(a,b)
        I_=AffinePunktoperatioin(I,a,b)
        return I_

q=255
B=mat([[180,80,140,110],
       [0,110,140,80],
       [255,110,180,140]])
B_=HistogrammDehnung(B,0.1,0.9)
print('B_=\n',B_)

# Onlinefrage Nr. 3:
# Wie groß ist die Summe aller Eintr¨age der neuen Bildmatrix aus Teilaufgabe 3.b?
u=0
v=0
s=0
while u<3:
    while v<4:
        s=s+B[u,v]
        v=v+1
    u=u+1
    v=0
print(s)

B_=
 [[255   0 153  77]
 [  0  77 153   0]
 [255  77 255 153]]
1455


<table><tr><td bgcolor=#F4A465>
<p align="center">
<font color=#228B22 size=5 face="San Francisco">
3.c<br />
</font>
<font color=#228B22 size=4 face="San Francisco">
Berechnen Sie das Ergebnisbild nach Ausführung eines Histogrammausgleichs auf B. Runden Sie dabei alle Einträge durch kaufmännisches Runden auf ganzzahlige Werte.
Onlinefrage Nr. 4:
Wie groß ist die Summe aller Einträge der neuen Bildmatrix aus Teilaufgabe 3.c? 
</font>
</p>
</td></tr></table>

In [74]:
# Histogrammausgleich
# Der Histogrammausgleich erhöht den Kontrast in Bereichendes Histogramms mit vielen Treffern
# Dadurch werden stark vertretene Grauwertbereiche für das Auge sichtbarer gemacht
# Der Histogrammausgleich ist eine homogene Punktoperation, jedoch keine affine Punktoperation
# Nachteil:
#   Obwohl der Histogrammausgleich in der Praxis in der
#   Regel den Kontrast erhöht, kann er auch zu einer
#   Verminderung des Kontrasts führen (siehe Übung)

import numpy as np
from numpy import *

# Algorithmus 13
def BrechneAkkumuliertesHistogramm(H):
    Ha=np.empty((q+1))
    Ha[0]=H[0]
    x=1
    while x<(q+1):
        Ha[x]=Ha[x-1]+H[x]
        x=x+1
    return Ha

# Algorithmus 9
def BrechneGrauwertHistogramm(I):
    x=0
    u=0
    v=0
    H=np.empty((q+1))
    while x<(q+1):
        H[x]=0
        x=x+1
    while v<4:
        while u<3:
            H[I[u,v]]=H[I[u,v]]+1
            u=u+1
        v=v+1
        u=0
    return H

def HistogrammAusgleich(I):
    H=BrechneGrauwertHistogramm(I)
    Ha=BrechneAkkumuliertesHistogramm(H)
    x=0
    Hn=np.empty((q+1))
    Hn_=np.empty((q+1))
    while x<(q+1):
        Hn[x]=q*Ha[x]/Ha[q]                  #Wegen Python3+ round() nicht wie gewuenscht funktioniert
        Hn_[x]=round(q*Ha[x]/Ha[q])
        if (Hn[x]-Hn_[x])>=0.5:
            Hn[x]=Hn_[x]+1
        else:
            Hn[x]=Hn_[x] 
        x=x+1
    u=0
    v=0
    I_=I
    while u<3:
        while v<4:
            I_[u,v]=Hn[I[u,v]]
            v=v+1
        u=u+1
        v=0
    return I_
        
        
q=255
B=mat([[180,80,140,110],
       [0,110,140,80],
       [255,110,180,140]])
B_=HistogrammAusgleich(B)
print('B_=\n',B_)

# Onlinefrage Nr. 4:
# Wie groß ist die Summe aller Eintr¨age der neuen Bildmatrix aus Teilaufgabe 3.c?
u=0
v=0
s=0
while u<3:
    while v<4:
        s=s+B[u,v]
        v=v+1
    u=u+1
    v=0
print(s)

B_=
 [[234  64 191 128]
 [ 21 128 191  64]
 [255 128 234 191]]
1829


<table><tr><td bgcolor=#F4A465>
<p align="center">
<font color=#228B22 size=5 face="San Francisco">
Aufgabe 4--Filter<br />
</font>
<font color=#228B22 size=4 face="San Francisco">
</font>
</p>
</td></tr></table>

B=([[20,20,20,20,50,50,50,20,20,20,20],
[20,20,20,20,50,50,50,20,20,20,20],
[20,20,20,20,50,50,50,20,20,20,20],
[20,20,20,20,50,50,50,20,20,20,20],
[20,20,20,20,50,50,50,20,20,20,20],
[20,20,20,20,50,50,50,20,20,20,20],
[20,20,20,20,50,50,50,20,20,20,20]]) 

<table><tr><td bgcolor=#F4A465>
<p align="center">
<font color=#228B22 size=5 face="San Francisco">
4.b<br />
</font>
<font color=#228B22 size=4 face="San Francisco">
Berechnen Sie die Bildmatrix B' durch Faltung der untenstehenden Bildmatrix B mit der
Filtermatrix aus Teilaufgabe 4.a. Runden Sie dabei alle Einträge durch kaufm¨ annisches
Runden auf ganzzahlige Werte. Fur Randpixel von B' soll kein Ergebnis berechnet werden,
d.h. berechnen Sie nur die Werte des inneren 5 × 9-Teils von B'.
</font>
</p>
</td></tr></table>

In [8]:
import numpy as np
from numpy import *
B=mat([[180,80,140,110],
       [0,110,140,80],
       [255,110,180,140]])
print(B)

[[180  80 140 110]
 [  0 110 140  80]
 [255 110 180 140]]


In [9]:
import matplotlib.pyplot as plt
import pylab
import cv2
import numpy as np
from numpy import *
img =mat([[20,20,20,20,50,50,50,20,20,20,20],
[20,20,20,20,50,50,50,20,20,20,20],
[20,20,20,20,50,50,50,20,20,20,20],
[20,20,20,20,50,50,50,20,20,20,20],
[20,20,20,20,50,50,50,20,20,20,20],
[20,20,20,20,50,50,50,20,20,20,20],
[20,20,20,20,50,50,50,20,20,20,20]])                        #在这里读取图片

fil = np.array([[1,2,1],                        #这个是设置的滤波，也就是卷积核
                [2,4,2],
                [1,2,1]])

res = cv2.filter2D(img,-1,fil)                      #使用opencv的卷积函数
print(res)

ModuleNotFoundError: No module named 'cv2'

In [33]:
import scipy.signal
import numpy as np

B=np.array([[20,20,20,20,50,50,50,20,20,20,20],
[20,20,20,20,50,50,50,20,20,20,20],
[20,20,20,20,50,50,50,20,20,20,20],
[20,20,20,20,50,50,50,20,20,20,20],
[20,20,20,20,50,50,50,20,20,20,20],
[20,20,20,20,50,50,50,20,20,20,20],
[20,20,20,20,50,50,50,20,20,20,20]])

# Filtermatrix
h=1/16*np.array([[1,2,1],                        
                [2,4,2],
                [1,2,1]])

B_=scipy.signal.convolve(B,h) #卷积运算
u_B_,v_B_=B_.shape
u0=int((u_B_-5)/2)
u1=int(u_B_-u0)
v0=int(u0)
v1=int(v_B_-v0)
H=B_[u0:u1,v0:v1]
u_H,v_H=H.shape
H_=np.empty((H.size),dtype=float).reshape(u_H,v_H).astype(int)
u=0
v=0
for u in range(u_H):
    for v in range(v_H):
        H_[u,v]=np.around(H[u,v])
        print(H_[u,v])

print(u_B_,v_B_)

print(H_)
print(H_[1,1])

20
20
28
42
50
42
28
20
20
20
20
28
42
50
42
28
20
20
20
20
28
42
50
42
28
20
20
20
20
28
42
50
42
28
20
20
20
20
28
42
50
42
28
20
20
9 13
[[20 20 28 42 50 42 28 20 20]
 [20 20 28 42 50 42 28 20 20]
 [20 20 28 42 50 42 28 20 20]
 [20 20 28 42 50 42 28 20 20]
 [20 20 28 42 50 42 28 20 20]]
20


In [114]:
print(round(3.5))

4


In [ ]:

 [20.    20.    27.5   42.5   50.    42.5   27.5   20.  20.  ]
 [ 5.    15.    20.    20.    27.5   42.5   50.    42.5   27.5   20.
  20.    15.     5.   ]
 [ 5.    15.    20.    20.    27.5   42.5   50.    42.5   27.5   20.
  20.    15.     5.   ]
 [ 5.    15.    20.    20.    27.5   42.5   50.    42.5   27.5   20.
  20.    15.     5.   ]
 [ 5.    15.    20.    20.    27.5   42.5   50.    42.5   27.5   20.
  20.    15.     5.   ]



In [ ]:
[[20,20,28,43,50,43,28,20,20],
 [20,20,28,43,50,43,28,20,20],
 [20,20,28,43,50,43,28,20,20],
 [20,20,28,43,50,43,28,20,20],
 [20,20,28,43,50,43,28,20,20],]

In [ ]:


import scipy.signal
import numpy as np
x=mat([[20,20,28,43,50,43,28,20,20],
 [20,20,28,43,50,43,28,20,20],
 [20,20,28,43,50,43,28,20,20],
 [20,20,28,43,50,43,28,20,20],
 [20,20,28,43,50,43,28,20,20],])
h=np.array([[-1,0,1],                        #这个是设置的滤波，也就是卷积核
                [-2,0,2],
                [-1,0,1]])

bb= scipy.signal.convolve(x,h) #卷积运算
print(bb)

In [ ]:
[32 -92 -88   0  88  92  32]
[32 -92 -88   0  88  92  32]
[32 -92 -88   0  88  92  32]
